/** ConfigManagement Actions */

export const LOAD_CURRENT_PAGE_TITLE = "LOAD_CURRENT_PAGE_TITLE";
export const LOAD_USERNAME = "LOAD_USERNAME";
export const LOGOUT = "LOGOUT";

// ACL Management Actions Type
export const LOADING_ASSIGNED_PAGE_PERMISSION = "LOADING_ASSIGNED_PAGE_PERMISSION";
export const LOADING_ASSIGNED_ACTION_PERMISSION = "LOADING_ASSIGNED_ACTION_PERMISSION";
export const LOADING_ASSIGNED_NODE_TYPE_PERMISSION = "LOADING_ASSIGNED_NODE_TYPE_PERMISSION";


// UploadConfigForm
export const LOADING_CONFIG_JSON = "LOADING_CONFIG_JSON";